@hostname = localhost
@port = 3300
@name = users
@createdAt = {{$localDatetime iso8601}}
@contentType = application/json

###

GET http://{{hostname}}:{{port}}/{{name}}

###

GET http://{{hostname}}:{{port}}/{{name}}/1

###

POST http://localhost:3300/register HTTP/1.1
{
  "email": "israel@teste.com",
  "password": "123456",
  "name": "israel"
}

