@hostname = localhost
@port = 3200
@name = users
@createdAt = {{$localDatetime iso8601}}
@contentType = application/json

###

GET http://{{hostname}}:{{port}}/{{name}}

###

GET http://{{hostname}}:{{port}}/{{name}}/1

###

POST http://{{hostname}}:{{port}}/register HTTP/1.1
content-type: application/json
{
  "email": "israel@teste.com",
  "password": "123456",
  "profile": "ADMIN"
}

###

POST http://localhost:3200/login
content-type: application/json

{
  "email": "israel@teste.com",
  "password": "123456",
}
